server.port: 8080

server.request.maxBodySize: 500mb #kb,mb
server.request.maxFileSize: 500mb #kb,mb (默认使用 maxBodySize 配置值)

solon.output.meta: 1
#solon.extend: luffy_ext #内部处理

luffy.center: "http://jtx.noear.org"
luffy.node: "localjt"

luffy.executor.default: "freemarker"
luffy.connection.pool: 0

luffy.db.name: "localjt"
luffy.db.schema: "PUBLIC"
luffy.db.url: "jdbc:h2:./luffy_ext/localjt;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
luffy.db.username: "sa"
luffy.db.password: "Ca78XJDFawZ5jaOL"
luffy.db.driverClassName: "org.h2.Driver"
